name: Qodana Code Quality
on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
          upload-result: true
          cache-default-branch-only: true
          args: |
            --baseline,qodana.baseline.sarif.json
            --fail-threshold,0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_807235408 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      
      - name: Upload SARIF file for GitHub Advanced Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json